package com.pgcompliance.constant;

public enum NotificationEventType {
    TENANT_ACCOUNT_ACTIVATED,
    TENANT_ROOM_ASSIGNED,
    TENANT_ROOM_TRANSFERRED,
    TENANT_MARKED_LEFT,
    ROOM_FULL,
    ROOM_AVAILABLE,
    ROOM_UNDER_REPAIR,
    COMPLAINT_CREATED,
    COMPLAINT_ASSIGNED,
    COMPLAINT_STATUS_CHANGED,
    COMPLAINT_REOPENED,
    COMPLAINT_OVERDUE,
    SYSTEM_FAILURE
}
